version: "3.2"
# コンテナの集まりの名前を定義
services:
    # 1つのコンテナの名前を定義
    # これ+プロジェクト(ディレクトリ)名がimage名となる
    exercise_rl:
        # ./にあるDockerfileを使う と言う意味
        build: .
        # image名をここで編集する(変える)
        image: rrrrind/exercise_rl
        # container名
        container_name: "exercise_rl"
        # ポート番号の指定(ホスト:コンテナ)
        ports:
          - 9990:9990
        # コンテナからローカルへバインドマウントする
        volumes: 
          - type: bind
            source: ./src
            target: /home/workspace/src
          - type: bind
            source: $HOME/.Xauthority
            target: /root/.Xauthority
        # 仮想ディスプレイの設定
        environment:
          - DISPLAY=host.docker.internal:0
        # コンテナを立ち上げた時に実行されるコマンド
        command: jupyter lab --ip=0.0.0.0 --port=9990 --allow-root --no-browser --notebook-dir="/home/workspace/src"