version: "3.2"
# コンテナの集まりの名前を定義
services:
    # 1つのコンテナの名前を定義
    # これ+プロジェクト(ディレクトリ)名がimage名となる
    rl_mc:
        # ./にあるDockerfileを使う と言う意味
        build: .
        # image名をここで編集する(変える)
        image: rrrrind/rl_mc
        # container名
        container_name: "rl_mc"
        # ポート番号の指定(ホスト:コンテナ)
        ports:
          - 9990:9990
        # コンテナからローカルへバインドマウントする
        volumes: 
          - type: bind
            source: ./src
            target: /home/workspace/src
        # コンテナを立ち上げた時に実行されるコマンド
        command: jupyter lab --ip=0.0.0.0 --port=9990 --allow-root --no-browser --notebook-dir="/home/workspace/src"